# Use a base image with your desired operating system
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy the local code to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the local code to the container
COPY . .

# Specify the command to run when the container starts
CMD ["node", "src/index.js"]